name: Lab05_

on:
  push:
    branches:
      - master
      
jobs:

  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: build banking
          shell: bash
          run: 
            cmake -H. -B_build && cmake --build _build
